### ISSUE TITLE
repeated number does not get translated

### ISSUE THREAD

**Issue by jobayerarman** [kingRayhan/bnnum#1]
if the string has repeated numbers like 11 or 22 then only the first one gets translated and the second number remains the same.

![image](https://user-images.githubusercontent.com/7051488/79114175-6fadef80-7da4-11ea-85a0-9c571f292d48.png)

**Comment by jobayerarman** [comment]
trying this fix for now

```javascript
const bnNum = (num, komma = false) => {
  const banglaNumber = {
    "0": "০",
    "1": "১",
    "2": "২",
    "3": "৩",
    "4": "৪",
    "5": "৫",
    "6": "৬",
    "7": "৭",
    "8": "৮",
    "9": "৯",
  };
  let str = `${num.toLocaleString('bn-BD', { useGrouping: komma })}`;

  for (var x in banglaNumber) {
    str = str.replace(new RegExp(x, "g"), banglaNumber[x]);
  }
  return str;
};
```

**Comment by kingRayhan** [comment]
Hey @jobayerarman 
Thank you so much for your contribution. I have updated the source codes. 😄
